version: "3.8"
services:
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=tao_api
    volumes:
      - "/tmp/pgdata/:/var/lib/postgresql/data"
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "8080:15672"
  celery:
    build: .
    volumes:
      - .:/code
    command: celery -A ming worker -l warning --concurrency=8 -Ofair
    depends_on:
      - postgres
      - rabbitmq
      - redis
    restart: "always"
  ming:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000 --noreload"
    volumes:
      - .:/code
    depends_on:
      - celery
    ports:
      - "8000:8000"
    restart: "always"
